### ISSUE TITLE
germline.bed - run bedtools merge to condense

### ISSUE THREAD

**Issue by keiranmraine** [cancerit/cgpPindel#31]
The germline.bed file just a set of ranges indicating an ins/del has occurred affecting the specified coordinate range.  Where these overlap they can be merged to reduce filesize.

Not urgent, only reduces file size by ~1.2%

**Comment by keiranmraine** [comment]
Tested with:

```
$ bedtools merge -i current.germline.bed > bedtools_merge.bed
$ perl perl/bin/pindel_germ_bed.pl -i current.flagged.vcf.gz > test_merge.bed
$ diff -s bedtools_merge.bed test_merge.bed
Files bedtools_merge.bed and test_merge.bed are identical
```

**Comment by keiranmraine** [comment]
Tested with:

```
$ bedtools merge -i current.germline.bed > bedtools_merge.bed
$ perl perl/bin/pindel_germ_bed.pl -i current.flagged.vcf.gz > test_merge.bed
$ diff -s bedtools_merge.bed test_merge.bed
Files bedtools_merge.bed and test_merge.bed are identical
```

Difference in lines:

```
$ wc -l current.germline.bed test_merge.bed
  406249 current.germline.bed
  399500 test_merge.bed
  805749 total
```

Difference in size:

```
$ ls -gG current.germline.bed test_merge.bed
-rw-r----- 1 8488155 Jan 11 05:20 current.germline.bed
-rw-r----- 1 8346927 Jan 11 15:11 test_merge.bed
```

**Comment by jsmedmar** [comment]
Hello @keiranmraine, I ran the latest version of cgpPindel and the germline.bed file was not generated automatically. Does this means that we have to run `pindel_germ_bed.pl` after pindel?

**Comment by keiranmraine** [comment]
We don't use the germline data for filtering SNV when processing Exomes as it's primarily to cope with minor alignment errors in repetitive regions.  Exomes being targeted to better defined regions means this is less useful.
