### ISSUE TITLE
lsof failed to start

### ISSUE THREAD

**Issue by JeremyBAdams** [cancerit/cgpPindel#50]
Hello,

I am attempting to run cgpPindel. However, when I run the pindel.pl command with all required parameters, I receive the following error message:

`"lsof" failed to start: "No such file or directory" at (eval 32) line 12.
 at /u/jadams/my_software/PCAP-core/lib/PCAP/Threaded.pm line 308`

Any idea how to go about fixing this?

Thanks

**Comment by keiranmraine** [comment]
You need a system tool called lsof installing.  On Ubuntu this is installed as:

```
apt-get install -yq --no-install-recommends lsof
```
