### ISSUE TITLE
Calling InDel with only tumor sample

### ISSUE THREAD

**Issue by tenglaowu** [cancerit/cgpPindel#54]
Dir sir,
Is there any possible to call somatic InDel without Normal sample but only tumor sample?

**Comment by keiranmraine** [comment]
As per the email conversation we had:

> cgpPindel is only designed to run with a single tumour and a matched normal.  However, you can run without a real matched normal dataset by creating an empty one for the '-normal' parameter.
>  
> A method to create the required files for a 'null' normal is described in the cgpPindel protocol paper under the 'pindel_np.gff3.gz' section of 'Support Protocol 2: Static Reference Files'.  You should use steps 1-3 to generate the empty dataset and then run analysis as normal.
