### ISSUE TITLE
When installing,t/1_pm_compile.t throws test error!

### ISSUE THREAD

**Issue by Blusea** [cancerit/cgpPindel#58]
```
/setup.sh   $cgpPindel_path
```
When installing, t/1_pm_compile.t throws test error!

 PERL_DL_NONLAZY=1
 "/share/app/perl-5.22.0/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/1_pm_compile.t ...................... 2/? 
\#   Failed test 'use Sanger::CGP::Pindel::InputGen;'
\#   at t/1_pm_compile.t line 56.
\#     Tried to use 'Sanger::CGP::Pindel::InputGen'.
\#     Error:  Attempt to reload threads.pm aborted.

THX!

**Comment by keiranmraine** [comment]
Hi,

Your perl install is not compiled with thread support:

```
$ perl --version

This is perl 5, version 18, subversion 4 (v5.18.4) built for x86_64-linux-thread-multi
...
```

Note the `....thread-multi` notice.

If you are able to use docker a pre built image is available supporting cgpPindel at [dockstore-cgp-wxs][https://github.com/cancerit/dockstore-cgpwxs]
