### ISSUE TITLE
using the docker container of cgpPINDEL

### ISSUE THREAD

**Issue by tanasa** [cancerit/cgpPindel#63]
Dear all, 

as I am new to Docker container technology, thought that i may ask please which precise steps shall I follow in order to install cgpPINDEL and its dependencies on our server, and have it ready to run ?

thank you, 

-- bogdan

**Comment by keiranmraine** [comment]
Depending on your data type please see the documentation on:

https://github.com/cancerit/dockstore-cgpwxs
or
https://github.com/cancerit/dockstore-cgpwgs

We cannot provide support for the installation of Docker itself.

If you provide further support in the use of the containers please raise a query on the above repositories.

Regards,
Keiran
