### ISSUE TITLE
using the docker container of cgpPINDEL

### ISSUE THREAD

**Issue by tanasa** [cancerit/cgpPindel#64]
Dear Keiran, and all,

if I may re-open an old message, thought that i may ask please which precise steps shall I follow in order to be able to use cgpPINDEL from a dockstore repository : 

https://github.com/cancerit/dockstore-cgpwgs

I would very much appreciate your help. Thanks a lot, 

-- bogdan

**Comment by keiranmraine** [comment]
If using via singularity or docker directly (not via CWL) replacing `ds-cgpwgs.pl ...` with `pindel.pl -h` will list the options you need to define.

You will need to expand the relevant reference archives and present them as a mounted file-system for this to be possible:

```
mkdir ref
tar --strip-components=1 -C ref -zxf ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/core_ref_GRCh37d5.tar.gz
tar --strip-components=1 -C ref -zxf ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/SNV_INDEL_ref_GRCh37d5-fragment.tar.gz
```
