### ISSUE TITLE
Pindel panel of normals

### ISSUE THREAD

**Issue by DominikGlodzik** [cancerit/cgpPindel#77]
Dear Colleagues,

I wonder if you could point me to details on how the normal panel for pindel was generated.

I can see the following flag:
```
F010
Pass when no overlapping records in Unmatched normal panel (tabix bed input).
```

Where could I find the number of sample in the panel of normals, as well as exact algorithm to determine F010 flagging? For example, is one read reporting an indel in the panel of normals enough to filter it out?

Kind regards
Dominik Głodzik

**Comment by keiranmraine** [comment]
Hi Dominik,

You can get the number of sample in the panel by reading the header of the normal panel file you have.

The minimum samples/var fraction is not well documented, it's hard coded as:

https://github.com/cancerit/cgpPindel/blob/da79133d7849117eca4ca3a22896d6b1256643b3/perl/bin/pindel_np_from_vcf.pl#L43-L44

So 3 samples, each with a VAF of > 5%

**Comment by keiranmraine** [comment]
More detail can be found in the protocols paper on how to generate a panel:

https://currentprotocols.onlinelibrary.wiley.com/doi/full/10.1002/0471250953.bi1507s52
