### ISSUE TITLE
Pindelpindel step hangs on high coverage chromosomes

### ISSUE THREAD

**Issue by mflevine** [cancerit/cgpPindel#88]
For a few of our samples where we received data >100x coverage, the pindelpindel step does not finish in chromosome 1/2 especially when there are whole chromosome amplifications. We have tried a few versions of pindel including the most recent (3.3.0) but this issue persists.

**Comment by keiranmraine** [comment]
What do you mean by "does not finish"?  Does the jobs run out of memory, disk or get killed by your scheduler for taking too long?

We have successfully run the cgpPindel container (v3.2.2) on an analysis for 125x "tumour" vs ~40x insilico normal.

The job was given 8 cpus (see `-c`) and ~60GB RAM.  This was run in the "on-shot" single process mode (no `-p`/`-i` options).

**Comment by keiranmraine** [comment]
I can also find 81x vs 138x (MT/WT).  These do take considerable time to complete chr1/2.  Somewhere in the 15-20h range.

**Comment by mflevine** [comment]
The job does not get killed due to memory. We are using a wrapper that resubmits the job if it is killed by runtime/memory. I have a couple instances of the job running for 2 weeks before I killed it and tried to downsample the bam. Our wrapper is using the `-p`/`-i` options and 1 cpu and 20G RAM per chromosome for the pindelpindel step. The particular sample I am testing on right now is a 130x/58x TN pair

**Comment by keiranmraine** [comment]
1. Can you confirm that duplicate marking has been performed on the input data?
2. Also how big are the generated input intermediates?
    * `tree -h $OUTPUTDIR` would be useful here.

Found our largest data set to be 600x/81x TN pair, max pindel chr wall time 41h.  This is on much older versions (April 2017), however there has been very little change to the core pindel c++ algorithm in that time.

**Comment by mflevine** [comment]
I increased the available RAM from that job to 30GB and was able to get the job to finish. So I think this was a memory issue but the job was not getting killed just stuck at the maximum allowed memory. I will test on couple other problematic samples. Thanks for your help!

**Comment by keiranmraine** [comment]
We had the thought that the issue could be the jobs being forced to swap data to disk, this would support the increased memory issue.  Under LSF (here) these get killed, but it would be configuration based.
