### ISSUE TITLE
Naive question, does increasing -c in pindel input will make it faster?

### ISSUE THREAD

**Issue by jsmedmar** [cancerit/cgpPindel#90]
The docs suggest to use 4 cores for Pindel Input, I'm just curious why 4? Would, say, 8 make it faster?

Thank you so much for your time in advance

**Comment by keiranmraine** [comment]
If you are running as `pindel.pl ...-p input -i N` then setting 4 is the maximum  as that is the max for the underlying process (beyond this it will get slower).

If you are running as a "one shot" either just defining `-p input` (no `-i`) or no `-p` at all, then 8 is valid.

Please note that from v3.2.0 onwards the input step is significantly faster anyway, so 2-3 is probably optimum.

I'd honestly recommend trying 1,2,3 and 4 to check the benefit, ultimately you only need to test this script for that bit:

https://github.com/cancerit/cgpPindel/blob/dev/perl/bin/pindel_input_gen.pl

**Comment by keiranmraine** [comment]
Also note:

https://github.com/cancerit/cgpPindel/blob/93dce3cb25adaa4b34c2e92d70b86f5c11ef9266/perl/bin/pindel_input_gen.pl#L85-L88

**Comment by jsmedmar** [comment]
This is really useful, thanks so much for clarifying
